### ISSUE TITLE
Monkey patching?

### ISSUE THREAD

**Issue by Hank95** [learn-co-curriculum/phase-3-ruby-oo-self-conclusion#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.
https://learning.flatironschool.com/courses/4206/pages/self-conclusion?module_item_id=272029

## What should be changed?
In the self quiz and in the conclusion there is mention of "monkey patching" with no explanation of what it actually is.  

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

**Comment by ihollander** [comment]
Hi @Hank95 , thanks for raising this issue. Here is a link to a lesson where Monkey Patching is discussed if you're curious to learn more: 

https://github.com/learn-co-curriculum/phase-3-ruby-oo-self-count-sentences-lab#monkey-patching

Depending on the program you're in, your instructors may choose not to deploy this particular lesson.
